// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ResourceIQ.Jcs.Infrastructure.Persistence;

#nullable disable

namespace ResourceIQ.Jcs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JcsDbContext))]
    [Migration("20260720090000_FormDrafts")]
    partial class FormDrafts
    {
    }
}
