// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceIQ.Jcs.Infrastructure.Persistence;

#nullable disable

namespace ResourceIQ.Jcs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JcsDbContext))]
    partial class JcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("CopyNumberSequence");

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CopyRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CopyRequestId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CopyContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CopyRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FormTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CopyRequestId")
                        .IsUnique();

                    b.HasIndex("FormTemplateId");

                    b.ToTable("CopyContents", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CopyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedCopyistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseBaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CaseFilingDate")
                        .HasColumnType("date");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CopyNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExpediteRequestNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MiscNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("OriginalCopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AssignedCopyistId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("OriginalCopyId");

                    b.HasIndex("RoomId");

                    b.HasIndex("State");

                    b.HasIndex("CourtId", "CaseBaseNumber")
                        .IsUnique()
                        .HasFilter("[Category] = 1");

                    b.HasIndex("CourtId", "CopyNumber")
                        .IsUnique()
                        .HasFilter("[CopyNumber] IS NOT NULL");

                    b.ToTable("CopyRequests", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CourtCopyCounter", b =>
                {
                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("CourtId", "Year");

                    b.ToTable("CourtCopyCounters", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValidationRulesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormFields", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Judge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Judges", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.JudgeRoom", b =>
                {
                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JudgeId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("JudgeRoom", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.MiscNumberCounter", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("ScopeKey", "Year");

                    b.ToTable("MiscNumberCounters", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.PanelMemberTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PanelMemberTitles", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.ParagraphTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FormTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("ParagraphTemplates", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumberingLevel")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("NumberingPolicy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "Code")
                        .IsUnique();

                    b.HasIndex("CourtId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.UserCourt", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CourtId");

                    b.HasIndex("CourtId");

                    b.ToTable("UserCourt", (string)null);
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CopyContent", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.CopyRequest", "CopyRequest")
                        .WithOne("Content")
                        .HasForeignKey("ResourceIQ.Jcs.Domain.Entities.CopyContent", "CopyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany()
                        .HasForeignKey("FormTemplateId");

                    b.Navigation("CopyRequest");

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CopyRequest", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.CopyRequest", null)
                        .WithMany()
                        .HasForeignKey("OriginalCopyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CourtCopyCounter", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.FormField", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany("Fields")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.JudgeRoom", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Judge", "Judge")
                        .WithMany("Rooms")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Room", "Room")
                        .WithMany("Judges")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judge");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.ParagraphTemplate", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany()
                        .HasForeignKey("FormTemplateId");

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Room", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.UserCourt", b =>
                {
                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceIQ.Jcs.Domain.Entities.User", "User")
                        .WithMany("Courts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.CopyRequest", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.FormTemplate", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Judge", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.Room", b =>
                {
                    b.Navigation("Judges");
                });

            modelBuilder.Entity("ResourceIQ.Jcs.Domain.Entities.User", b =>
                {
                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
